# Generated by Django 3.0.6 on 2020-05-27 20:04

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200527_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='social_link',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='about',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка для связи'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True, verbose_name='Телефон для связи'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(max_length=16, verbose_name='Отображаемое имя'),
        ),
    ]
