# Generated by Django 3.0.6 on 2020-05-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200527_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='messenger',
            field=models.CharField(blank=True, choices=[('media/messengers/telegram-app.png', 'Telegram'), ('media/messengers/viber.png', 'Viber'), ('media/messengers/whatsapp.png', 'Whatsapp')], max_length=250, null=True, verbose_name='Мессенджер'),
        ),
    ]
