# Generated by Django 3.0.6 on 2020-06-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_userprofile_messenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='profile/default_profile.png', upload_to='profile/', verbose_name='Аватар'),
        ),
    ]
