# Generated by Django 3.0.6 on 2020-05-06 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20200504_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Тип контента')),
            ],
        ),
        migrations.AlterModelOptions(
            name='advert',
            options={'verbose_name': 'Обьявление', 'verbose_name_plural': 'Обьявления'},
        ),
        migrations.AlterField(
            model_name='advert',
            name='content',
            field=models.TextField(max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='board.Platform', verbose_name='Платформа'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='published',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='title',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Платформа'),
        ),
        migrations.AddField(
            model_name='advert',
            name='advert_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='board.AdvertCategory', verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advert',
            name='content_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='board.ContentType', verbose_name='Тип контента'),
            preserve_default=False,
        ),
    ]
