# Generated by Django 3.0.6 on 2020-05-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20200509_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='img',
            field=models.ImageField(null=True, upload_to='platform', verbose_name='Изображение'),
        ),
    ]
